# Generated by Django 4.2.1 on 2024-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["-year_started"],
                "verbose_name": "experiencia",
                "verbose_name_plural": "experiencias",
            },
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="date",
            new_name="year_started",
        ),
        migrations.AddField(
            model_name="experience",
            name="year_ended",
            field=models.DateField(blank=True, null=True),
        ),
    ]
