# Generated by Django 4.2.1 on 2024-11-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0003_alter_experience_year_ended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="year_ended",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="year_started",
            field=models.DateField(),
        ),
    ]
