# Generated by Django 4.2.1 on 2024-11-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0004_alter_experience_year_ended_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["-date_started"],
                "verbose_name": "experiencia",
                "verbose_name_plural": "experiencias",
            },
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="year_ended",
            new_name="date_ended",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="year_started",
            new_name="date_started",
        ),
    ]
